#COMPOSEFILE
services:
  postgres:
    image: postgres:16-alpine
    container_name: rechini-postgres
    restart: always
    environment:
      POSTGRES_DB: rechini_village
      POSTGRES_USER: rechini_user
      POSTGRES_PASSWORD: change_this_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/src/sql/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
    ports:
      - "5433:5432"

  backend:
    build: ./backend
    container_name: rechini-backend
    restart: always
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
    expose:
      - "5000"

  frontend:
    build: ./frontend
    container_name: rechini-frontend
    restart: always
    depends_on:
      - backend
    expose:
      - "80"

  nginx:
    image: nginx:alpine
    container_name: rechini-nginx
    restart: always
    depends_on:
      - frontend
      - backend
    ports:
      - "8088:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  postgres_data:
